version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: yura
            POSTGRES_PASSWORD: 1
            POSTGRES_DB: postgres
        volumes:
           - ./init.sql:/docker-entrypoint-initdb.d/init.sql




    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080